---
- name: Reload systemctl
  command: systemctl daemon-reload

- name: Reload initd
  command: initctl reload-configuration

- name: Restart kafka service
  service:
    name: kafka
    state: restarted

- name: Restart kafka systemd
  systemd:
    name: kafka
    state: restarted
    daemon_reload: yes

- name: Restart zookeeper service
  service:
    name: zookeeper
    state: restarted

- name: Restart zookeeper systemd
  systemd:
    name: zookeeper
    state: restarted
    daemon_reload: yes